<Project>
  
    <PropertyGroup>
        <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
        <TargetFramework>net10.0-windows</TargetFramework>
        <BinaryDirectory>..\Binary</BinaryDirectory>
    </PropertyGroup>

    <PropertyGroup>
        <WarningLevel>4</WarningLevel>
        <Deterministic>false</Deterministic>
        <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
        <Nullable>disable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <BaseIntermediateOutputPath>$(SolutionDir)obj\projects\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
        <BaseOutputPath>$(SolutionDir)bin\</BaseOutputPath>
        <OutputPath>$(BaseOutputPath)$(Configuration)\</OutputPath>
    </PropertyGroup>

    <PropertyGroup>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <Company>Pavel Torgashov</Company>
        <Product>FastColoredTextBox</Product>
        <Description>Fast colored textbox control</Description>
        <Copyright>© Pavel Torgashov, 2011-2016, pavel_torgashov@ukr.net.</Copyright>
        <VersionRevision>$([System.DateTime]::UtcNow.Subtract($([System.DateTime]::new(2001,1,1))).TotalDays.ToString("0"))</VersionRevision>
        <Version>2.16.26.$(VersionRevision)</Version>
    </PropertyGroup>

</Project>