<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <UseWindowsForms>true</UseWindowsForms>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>$(NoWarn);WFO1000</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\FastColoredTextBox\FastColoredTextBox.csproj" />
        <Reference Include="TabStrip" />
    </ItemGroup>

</Project>