<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <UseWindowsForms>true</UseWindowsForms>
        <RootNamespace>Tester</RootNamespace>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>$(NoWarn);WFO1000</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\FastColoredTextBox\FastColoredTextBox.csproj" />
        <Reference Include="TabStrip" />
    </ItemGroup>

    <Target Name="CopyOutputToBinaryDirectory" AfterTargets="Build">
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(BinaryDirectory)" />
        <Copy SourceFiles="$(OutDir)$(AssemblyName).exe" DestinationFolder="$(BinaryDirectory)" />
        <Copy SourceFiles="$(OutDir)$(AssemblyName).runtimeconfig.json" DestinationFolder="$(BinaryDirectory)" />
        <Copy SourceFiles="$(OutDir)TabStrip.dll" DestinationFolder="$(BinaryDirectory)" />
        <Copy SourceFiles="$(ProjectDir)htmlDesc.xml" DestinationFolder="$(BinaryDirectory)" />
    </Target>

</Project>