<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseWindowsForms>true</UseWindowsForms>
        <RootNamespace>FastColoredTextBoxNS</RootNamespace>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>$(NoWarn);WFO1000;CS1572;CS1573;CS1584;CS1591;CS1658</NoWarn>
    </PropertyGroup>

    <Target Name="CopyOutputToBinaryDirectory" AfterTargets="Pack">
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(BinaryDirectory)" />
        <Copy SourceFiles="$(DocumentationFile)" DestinationFolder="$(BinaryDirectory)" />
        <Copy SourceFiles="$(OutDir)$(PackageId).$(PackageVersion).nupkg" DestinationFolder="$(BinaryDirectory)" />
    </Target>

    <PropertyGroup>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <PackageId>FastColoredTextBox.NET10</PackageId>
        <Title>.NET10/VS2026 fork of $(AssemblyName)</Title>
        <PackageProjectUrl>https://github.com/vurdalakov/FastColoredTextBox.NET10</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <RepositoryUrl>https://github.com/vurdalakov/FastColoredTextBox.NET10</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>FastColoredTextBox;Scintilla;WinForms;text editor;syntax highlighting</PackageTags>
        <PackageReleaseNotes>A .NET 10 / VS 2026 fork of the FastColoredTextBox project by Pavel Torgashov.</PackageReleaseNotes>
        <PackageLicenseFile>license.txt</PackageLicenseFile>
        <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    </PropertyGroup>

    <ItemGroup>
      <None Include="..\license.txt">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
      <None Include="..\README.md">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
    </ItemGroup>

</Project>
